### ISSUE TITLE
[Epic] Design / UX issues

### ISSUE THREAD

**Issue by stephanie-anderson** [getsentry/spotlight#125]
This is an epic for all the pre-launch design and UX issues that have been noticed.

```[tasklist]
### Issues
- [ ] https://github.com/getsentry/spotlight/issues/129
- [ ] https://github.com/getsentry/spotlight/issues/126
- [ ] https://github.com/getsentry/spotlight/issues/127
- [ ] https://github.com/getsentry/spotlight/issues/128
```

**Comment by HazAT** [comment]
Let's just keep the individual issues
