### ISSUE TITLE
Finalize Sentry integration refactor (finalize integration API and routing)

### ISSUE THREAD

**Issue by Lms24** [getsentry/spotlight#19]
```[tasklist]
### Tasks
- [x] Figure out nested inter- and intra-tab routing
- [x] Remove all event/trace/span ids from navigation context
- [x] Remove integrations from navigation context and remove the context all together
- [x] Figure out/bring back [ESC] key functionality
```
